// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusKHv3LkjB_zpiywGz-hbkF8iPhF2Pbs',
    appId: '1:37081076374:web:d59863379ce2df08efe8b7',
    messagingSenderId: '37081076374',
    projectId: 'stock-market-a3381',
    authDomain: 'stock-market-a3381.firebaseapp.com',
    storageBucket: 'stock-market-a3381.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQqGcp4gMEayZYhDFpw9Bsf0uTCgNa0c',
    appId: '1:37081076374:android:07fbcf5da60a23b3efe8b7',
    messagingSenderId: '37081076374',
    projectId: 'stock-market-a3381',
    storageBucket: 'stock-market-a3381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXVenqt5Wwvk4r4jMhFLipPFtgGdztTg',
    appId: '1:37081076374:ios:2ff9fb95de25121fefe8b7',
    messagingSenderId: '37081076374',
    projectId: 'stock-market-a3381',
    storageBucket: 'stock-market-a3381.appspot.com',
    iosBundleId: 'com.example.stockMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJXVenqt5Wwvk4r4jMhFLipPFtgGdztTg',
    appId: '1:37081076374:ios:fb7a1618c109c1b0efe8b7',
    messagingSenderId: '37081076374',
    projectId: 'stock-market-a3381',
    storageBucket: 'stock-market-a3381.appspot.com',
    iosBundleId: 'com.example.stockMarket.RunnerTests',
  );
}

